--- 
 - debug:
    msg: "System {{ inventory_hostname }} has OS {{ ansible_distribution }}"
 - name: ntp additional packages 
   become: yes
   yum: pkg={{ item }} 
        state=present 
        update_cache=yes
   with_items: 
     - ntp
   when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
   notify: 
         - Start ntpd
